apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: payetonkawa
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.2.1
    helm:
      values: |
        fullnameOverride: "postgresql"
        auth:
          existingSecret: "postgresql-admin"
          secretKeys:
            adminPasswordKey: "POSTGRESQL_ADMIN_PASSWORD"
        primary:
          persistence:
            enabled: true
            storageClass: local-path
            size: 5Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
