apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: payetonkawa
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.3.2
    helm:
      values: |
        fullnameOverride: "rabbitmq"
        auth:
          existingPasswordSecret: "rabbitmq-auth"
          username: "monuser"
          passwordSecretKey: "RABBITMQ_PASSWORD"
