apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ptk-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ptk-ingress-nginx
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: 1.13.1
    chart: cert-manager
    helm:
      values: |
        fullnameOverride: cert-manager
        installCRDs: true