apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: cert-manager
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  source:
    path: resources/cluster-issuer
    repoURL: 'https://github.com/PayeTonKawa2025/infra-gitops.git'
    targetRevision: HEAD
    directory:
      recurse: true